"""Config model, tmux.conf generation and (best-effort) parsing."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import date

from .options import CATEGORIES, OPTIONS, OPTIONS_BY_NAME, Option

# Options whose values contain backslash escapes that tmux should interpret
# (e.g. "\e[1;5A"); these are written in double quotes without escaping "\".
BACKSLASH_ESCAPED = {"user-keys"}

# Array options that must always be written with explicit indexes, because
# tmux splits unindexed values on commas.
INDEX_ONLY = {"status-format"}

KEY_TABLES = ["prefix", "root", "copy-mode", "copy-mode-vi"]

_SAFE = re.compile(r"^[A-Za-z0-9_./:@+=,^*!&()<>?\[\]|-]+$")


def quote(value: str) -> str:
    """Quote *value* so tmux's config parser reads it back verbatim."""
    if value and _SAFE.match(value):
        return value
    if "'" not in value:
        return f"'{value}'"
    escaped = (value.replace("\\", "\\\\").replace('"', '\\"')
               .replace("$", "\\$"))
    return f'"{escaped}"'


def quote_escaped(value: str) -> str:
    """Double-quote *value* leaving backslash escapes for tmux to expand."""
    return '"' + value.replace('"', '\\"').replace("$", "\\$") + '"'


def quote_key(key: str) -> str:
    """Quote a key name for bind-key/unbind-key."""
    if key == "-":
        return key
    return quote(key)


@dataclass
class Binding:
    key: str
    command: str
    table: str = "prefix"
    repeat: bool = False
    note: str = ""

    def render(self) -> str:
        parts = ["bind"]
        if self.repeat:
            parts.append("-r")
        if self.note:
            parts += ["-N", quote(self.note)]
        if self.table == "root":
            parts.append("-n")
        elif self.table != "prefix":
            parts += ["-T", quote(self.table)]
        parts += [quote_key(self.key), self.command.strip()]
        return " ".join(parts)


@dataclass
class Unbind:
    key: str  # empty string means "all keys in the table"
    table: str = "prefix"

    def render(self) -> str:
        parts = ["unbind"]
        if not self.key:
            parts.append("-a")
        if self.table == "root":
            parts.append("-n")
        elif self.table != "prefix" or not self.key:
            parts += ["-T", quote(self.table)]
        if self.key:
            parts.append(quote_key(self.key))
        return " ".join(parts)


@dataclass
class Config:
    # option name -> value (str, or list[str] for list options). Only
    # options present here are written to the file.
    values: dict = field(default_factory=dict)
    # list options that append to tmux's defaults instead of replacing them
    list_append: set = field(default_factory=set)
    unbinds: list = field(default_factory=list)
    bindings: list = field(default_factory=list)
    extra: str = ""

    def set(self, name: str, value) -> None:
        self.values[name] = value

    def unset(self, name: str) -> None:
        self.values.pop(name, None)
        self.list_append.discard(name)


def render_option(opt: Option, value, append: bool = False) -> list[str]:
    q = quote_escaped if opt.name in BACKSLASH_ESCAPED else quote
    if opt.type != "list":
        return [f"set {opt.flags} {opt.name} {q(str(value))}"]
    items = [v for v in value if v != ""]
    if append and opt.name not in INDEX_ONLY:
        aflags = "-a" + opt.flags[1:]
        return [f"set {aflags} {opt.name} {q(v)}" for v in items]
    lines = [f"set {opt.flags} {opt.name} ''"]
    lines += [f"set {opt.flags} {opt.name}[{i}] {q(v)}"
              for i, v in enumerate(items)]
    return lines


def generate(cfg: Config, header: bool = True) -> str:
    out: list[str] = []
    if header:
        out += ["# tmux configuration",
                f"# Generated by tmux-config-generator on {date.today():%Y-%m-%d}",
                ""]
    for cat, title in CATEGORIES:
        lines = []
        for opt in OPTIONS:
            if opt.category == cat and opt.name in cfg.values:
                lines += render_option(opt, cfg.values[opt.name],
                                       opt.name in cfg.list_append)
        if lines:
            out += [f"# --- {title} ---", *lines, ""]
    if cfg.unbinds:
        out += ["# --- Unbound keys ---", *(u.render() for u in cfg.unbinds), ""]
    if cfg.bindings:
        out.append("# --- Key bindings ---")
        for table in _tables_in_order(cfg.bindings):
            out += [b.render() for b in cfg.bindings if b.table == table]
        out.append("")
    if cfg.extra.strip():
        out += ["# --- Custom ---", cfg.extra.strip("\n"), ""]
    return "\n".join(out).rstrip("\n") + "\n"


def _tables_in_order(bindings) -> list[str]:
    tables = [t for t in KEY_TABLES if any(b.table == t for b in bindings)]
    for b in bindings:
        if b.table not in tables:
            tables.append(b.table)
    return tables


# ---------------------------------------------------------------------------
# Parsing


@dataclass
class Token:
    text: str   # unquoted value
    start: int  # offset of the raw token in the line
    end: int


def tokenize(line: str) -> list[Token]:
    """Split one logical config line into words, tmux-style.

    Handles quotes, backslash escapes, `{ ... }` blocks (kept as one raw
    token) and `#` comments. Raises ValueError on unbalanced quotes/braces.
    """
    tokens: list[Token] = []
    i, n = 0, len(line)
    while i < n:
        while i < n and line[i] in " \t":
            i += 1
        if i >= n or line[i] == "#":
            break
        start = i
        if line[i] == "{":
            depth = 0
            while i < n:
                c = line[i]
                if c in "'\"":
                    i = _skip_quoted(line, i)
                    continue
                if c == "{":
                    depth += 1
                elif c == "}":
                    depth -= 1
                    if depth == 0:
                        i += 1
                        break
                i += 1
            if depth:
                raise ValueError("unbalanced braces")
            tokens.append(Token(line[start:i], start, i))
            continue
        buf = []
        while i < n and line[i] not in " \t":
            c = line[i]
            if c == "'":
                j = line.find("'", i + 1)
                if j < 0:
                    raise ValueError("unterminated quote")
                buf.append(line[i + 1:j])
                i = j + 1
            elif c == '"':
                i += 1
                while i < n and line[i] != '"':
                    if line[i] == "\\" and i + 1 < n:
                        i += 1
                    buf.append(line[i])
                    i += 1
                if i >= n:
                    raise ValueError("unterminated quote")
                i += 1
            elif c == "\\" and i + 1 < n:
                buf.append(line[i + 1])
                i += 2
            else:
                buf.append(c)
                i += 1
        tokens.append(Token("".join(buf), start, i))
    return tokens


def _skip_quoted(line: str, i: int) -> int:
    q = line[i]
    i += 1
    while i < len(line) and line[i] != q:
        if q == '"' and line[i] == "\\":
            i += 1
        i += 1
    return i + 1


def logical_lines(text: str):
    """Yield logical lines, joining backslash continuations and brace blocks."""
    pending = ""
    for raw in text.splitlines():
        if pending:
            pending += "\n" + raw
        else:
            pending = raw
        if pending.endswith("\\") and not pending.endswith("\\\\"):
            pending = pending[:-1]
            continue
        try:
            tokenize(pending)
        except ValueError:
            continue  # unbalanced: keep accumulating
        yield pending
        pending = ""
    if pending:
        yield pending


_GENERATED_COMMENT = re.compile(
    r"^# (tmux configuration|Generated by tmux-config-generator|--- .* ---)")

_SET_CMDS = {"set", "set-option", "setw", "set-window-option"}
_BIND_CMDS = {"bind", "bind-key"}
_UNBIND_CMDS = {"unbind", "unbind-key"}


def parse(text: str) -> Config:
    """Parse a tmux.conf into a Config.

    Recognised `set`, `bind` and `unbind` lines are loaded into the model;
    everything else (hooks, if-shell, source-file, plugins, ...) is kept
    verbatim in `extra`.
    """
    cfg = Config()
    extra: list[str] = []
    for line in logical_lines(text):
        stripped = line.strip()
        if _GENERATED_COMMENT.match(stripped):
            continue
        try:
            tokens = tokenize(line)
        except ValueError:
            tokens = []
        handled = False
        if tokens:
            cmd = tokens[0].text
            # A set/unbind line chaining several commands with ';' is kept
            # verbatim; for bind, ';' belongs to the bound command.
            chained = any(line[t.start:t.end].endswith(";") for t in tokens)
            if chained and cmd not in _BIND_CMDS:
                pass
            elif cmd in _SET_CMDS:
                handled = _parse_set(cfg, line, tokens)
            elif cmd in _BIND_CMDS:
                handled = _parse_bind(cfg, line, tokens)
            elif cmd in _UNBIND_CMDS:
                handled = _parse_unbind(cfg, tokens)
        if not handled:
            extra.append(line)
    # Drop leading/trailing blank lines from the leftover text.
    cfg.extra = "\n".join(extra).strip("\n")
    cfg.extra = re.sub(r"\n{3,}", "\n\n", cfg.extra)
    return cfg


def _split_flags(tokens: list[Token], with_arg: str):
    """Split getopt-style flags. Returns (flags set, {flag: arg}, rest)."""
    flags, args = set(), {}
    i = 1
    while i < len(tokens):
        t = tokens[i].text
        if t == "--":
            i += 1
            break
        if not t.startswith("-") or t == "-":
            break
        j = 1
        while j < len(t):
            f = t[j]
            if f in with_arg:
                val = t[j + 1:]
                if not val:
                    i += 1
                    if i >= len(tokens):
                        raise ValueError("missing flag argument")
                    val = tokens[i].text
                args[f] = val
                break
            flags.add(f)
            j += 1
        i += 1
    return flags, args, i


def _parse_set(cfg: Config, line: str, tokens: list[Token]) -> bool:
    try:
        flags, args, i = _split_flags(tokens, "t")
    except ValueError:
        return False
    if args or flags - set("gswpaoq") or "g" not in flags and "s" not in flags:
        return False
    if len(tokens) - i != 2:
        return False
    name, value = tokens[i].text, tokens[i + 1].text
    m = re.match(r"^([a-z0-9-]+)(?:\[(\d+)\])?$", name)
    if not m or m.group(1) not in OPTIONS_BY_NAME:
        return False
    opt = OPTIONS_BY_NAME[m.group(1)]
    index = m.group(2)
    if opt.name in BACKSLASH_ESCAPED:
        raw = line[tokens[i + 1].start:tokens[i + 1].end]
        if raw.startswith('"') and raw.endswith('"'):
            value = raw[1:-1].replace('\\"', '"').replace("\\$", "$")
    if opt.type != "list":
        if index is not None or "a" in flags:
            return False
        cfg.set(opt.name, value)
        return True
    items = cfg.values.setdefault(opt.name, [])
    if index is not None:
        idx = int(index)
        while len(items) <= idx:
            items.append("")
        items[idx] = value
    elif "a" in flags:
        if opt.name not in cfg.list_append and not items:
            cfg.list_append.add(opt.name)
        items.append(value)
    else:
        items.clear()
        cfg.list_append.discard(opt.name)
        if value:
            items.append(value)
    return True


def _parse_bind(cfg: Config, line: str, tokens: list[Token]) -> bool:
    try:
        flags, args, i = _split_flags(tokens, "TN")
    except ValueError:
        return False
    if flags - set("nr") or i + 1 >= len(tokens):
        return False
    table = "root" if "n" in flags else args.get("T", "prefix")
    key = tokens[i].text
    command = line[tokens[i].end:].strip()
    cfg.bindings.append(Binding(key=key, command=command, table=table,
                                repeat="r" in flags, note=args.get("N", "")))
    return True


def _parse_unbind(cfg: Config, tokens: list[Token]) -> bool:
    try:
        flags, args, i = _split_flags(tokens, "T")
    except ValueError:
        return False
    if flags - set("anq"):
        return False
    table = "root" if "n" in flags else args.get("T", "prefix")
    rest = tokens[i:]
    if "a" in flags:
        if rest:
            return False
        cfg.unbinds.append(Unbind("", table))
    else:
        if len(rest) != 1:
            return False
        cfg.unbinds.append(Unbind(rest[0].text, table))
    return True
