"""Default tmux 3.4 key bindings (from `tmux -f /dev/null list-keys`).

Rows are (table, key, repeat, command, note).
"""

DEFAULT_BINDINGS = [
    ('copy-mode', 'C-Space', False, 'send-keys -X begin-selection', ''),
    ('copy-mode', 'C-a', False, 'send-keys -X start-of-line', ''),
    ('copy-mode', 'C-b', False, 'send-keys -X cursor-left', ''),
    ('copy-mode', 'C-c', False, 'send-keys -X cancel', ''),
    ('copy-mode', 'C-e', False, 'send-keys -X end-of-line', ''),
    ('copy-mode', 'C-f', False, 'send-keys -X cursor-right', ''),
    ('copy-mode', 'C-g', False, 'send-keys -X clear-selection', ''),
    ('copy-mode', 'C-k', False, 'send-keys -X copy-pipe-end-of-line-and-cancel', ''),
    ('copy-mode', 'C-n', False, 'send-keys -X cursor-down', ''),
    ('copy-mode', 'C-p', False, 'send-keys -X cursor-up', ''),
    ('copy-mode', 'C-r', False, 'command-prompt -i -I "#{pane_search_string}" -T search -p "(search up)" { send-keys -X search-backward-incremental "%%" }', ''),
    ('copy-mode', 'C-s', False, 'command-prompt -i -I "#{pane_search_string}" -T search -p "(search down)" { send-keys -X search-forward-incremental "%%" }', ''),
    ('copy-mode', 'C-v', False, 'send-keys -X page-down', ''),
    ('copy-mode', 'C-w', False, 'send-keys -X copy-pipe-and-cancel', ''),
    ('copy-mode', 'Escape', False, 'send-keys -X cancel', ''),
    ('copy-mode', 'Space', False, 'send-keys -X page-down', ''),
    ('copy-mode', ',', False, 'send-keys -X jump-reverse', ''),
    ('copy-mode', ';', False, 'send-keys -X jump-again', ''),
    ('copy-mode', 'F', False, 'command-prompt -1 -p "(jump backward)" { send-keys -X jump-backward "%%" }', ''),
    ('copy-mode', 'N', False, 'send-keys -X search-reverse', ''),
    ('copy-mode', 'P', False, 'send-keys -X toggle-position', ''),
    ('copy-mode', 'R', False, 'send-keys -X rectangle-toggle', ''),
    ('copy-mode', 'T', False, 'command-prompt -1 -p "(jump to backward)" { send-keys -X jump-to-backward "%%" }', ''),
    ('copy-mode', 'X', False, 'send-keys -X set-mark', ''),
    ('copy-mode', 'f', False, 'command-prompt -1 -p "(jump forward)" { send-keys -X jump-forward "%%" }', ''),
    ('copy-mode', 'g', False, 'command-prompt -p "(goto line)" { send-keys -X goto-line "%%" }', ''),
    ('copy-mode', 'n', False, 'send-keys -X search-again', ''),
    ('copy-mode', 'q', False, 'send-keys -X cancel', ''),
    ('copy-mode', 'r', False, 'send-keys -X refresh-from-pane', ''),
    ('copy-mode', 't', False, 'command-prompt -1 -p "(jump to forward)" { send-keys -X jump-to-forward "%%" }', ''),
    ('copy-mode', 'MouseDown1Pane', False, 'select-pane', ''),
    ('copy-mode', 'MouseDrag1Pane', False, 'select-pane \\; send-keys -X begin-selection', ''),
    ('copy-mode', 'MouseDragEnd1Pane', False, 'send-keys -X copy-pipe-and-cancel', ''),
    ('copy-mode', 'WheelUpPane', False, 'select-pane \\; send-keys -X -N 5 scroll-up', ''),
    ('copy-mode', 'WheelDownPane', False, 'select-pane \\; send-keys -X -N 5 scroll-down', ''),
    ('copy-mode', 'DoubleClick1Pane', False, 'select-pane \\; send-keys -X select-word \\; run-shell -d 0.3 \\; send-keys -X copy-pipe-and-cancel', ''),
    ('copy-mode', 'TripleClick1Pane', False, 'select-pane \\; send-keys -X select-line \\; run-shell -d 0.3 \\; send-keys -X copy-pipe-and-cancel', ''),
    ('copy-mode', 'Home', False, 'send-keys -X start-of-line', ''),
    ('copy-mode', 'End', False, 'send-keys -X end-of-line', ''),
    ('copy-mode', 'NPage', False, 'send-keys -X page-down', ''),
    ('copy-mode', 'PPage', False, 'send-keys -X page-up', ''),
    ('copy-mode', 'Up', False, 'send-keys -X cursor-up', ''),
    ('copy-mode', 'Down', False, 'send-keys -X cursor-down', ''),
    ('copy-mode', 'Left', False, 'send-keys -X cursor-left', ''),
    ('copy-mode', 'Right', False, 'send-keys -X cursor-right', ''),
    ('copy-mode', 'M-C-b', False, 'send-keys -X previous-matching-bracket', ''),
    ('copy-mode', 'M-C-f', False, 'send-keys -X next-matching-bracket', ''),
    ('copy-mode', 'M-1', False, 'command-prompt -N -I 1 -p (repeat) { send-keys -N "%%" }', ''),
    ('copy-mode', 'M-2', False, 'command-prompt -N -I 2 -p (repeat) { send-keys -N "%%" }', ''),
    ('copy-mode', 'M-3', False, 'command-prompt -N -I 3 -p (repeat) { send-keys -N "%%" }', ''),
    ('copy-mode', 'M-4', False, 'command-prompt -N -I 4 -p (repeat) { send-keys -N "%%" }', ''),
    ('copy-mode', 'M-5', False, 'command-prompt -N -I 5 -p (repeat) { send-keys -N "%%" }', ''),
    ('copy-mode', 'M-6', False, 'command-prompt -N -I 6 -p (repeat) { send-keys -N "%%" }', ''),
    ('copy-mode', 'M-7', False, 'command-prompt -N -I 7 -p (repeat) { send-keys -N "%%" }', ''),
    ('copy-mode', 'M-8', False, 'command-prompt -N -I 8 -p (repeat) { send-keys -N "%%" }', ''),
    ('copy-mode', 'M-9', False, 'command-prompt -N -I 9 -p (repeat) { send-keys -N "%%" }', ''),
    ('copy-mode', 'M-<', False, 'send-keys -X history-top', ''),
    ('copy-mode', 'M->', False, 'send-keys -X history-bottom', ''),
    ('copy-mode', 'M-R', False, 'send-keys -X top-line', ''),
    ('copy-mode', 'M-b', False, 'send-keys -X previous-word', ''),
    ('copy-mode', 'M-f', False, 'send-keys -X next-word-end', ''),
    ('copy-mode', 'M-m', False, 'send-keys -X back-to-indentation', ''),
    ('copy-mode', 'M-r', False, 'send-keys -X middle-line', ''),
    ('copy-mode', 'M-v', False, 'send-keys -X page-up', ''),
    ('copy-mode', 'M-w', False, 'send-keys -X copy-pipe-and-cancel', ''),
    ('copy-mode', 'M-x', False, 'send-keys -X jump-to-mark', ''),
    ('copy-mode', 'M-{', False, 'send-keys -X previous-paragraph', ''),
    ('copy-mode', 'M-}', False, 'send-keys -X next-paragraph', ''),
    ('copy-mode', 'M-Up', False, 'send-keys -X halfpage-up', ''),
    ('copy-mode', 'M-Down', False, 'send-keys -X halfpage-down', ''),
    ('copy-mode', 'C-Up', False, 'send-keys -X scroll-up', ''),
    ('copy-mode', 'C-Down', False, 'send-keys -X scroll-down', ''),
    ('copy-mode-vi', 'C-b', False, 'send-keys -X page-up', ''),
    ('copy-mode-vi', 'C-c', False, 'send-keys -X cancel', ''),
    ('copy-mode-vi', 'C-d', False, 'send-keys -X halfpage-down', ''),
    ('copy-mode-vi', 'C-e', False, 'send-keys -X scroll-down', ''),
    ('copy-mode-vi', 'C-f', False, 'send-keys -X page-down', ''),
    ('copy-mode-vi', 'C-h', False, 'send-keys -X cursor-left', ''),
    ('copy-mode-vi', 'C-j', False, 'send-keys -X copy-pipe-and-cancel', ''),
    ('copy-mode-vi', 'Enter', False, 'send-keys -X copy-pipe-and-cancel', ''),
    ('copy-mode-vi', 'C-u', False, 'send-keys -X halfpage-up', ''),
    ('copy-mode-vi', 'C-v', False, 'send-keys -X rectangle-toggle', ''),
    ('copy-mode-vi', 'C-y', False, 'send-keys -X scroll-up', ''),
    ('copy-mode-vi', 'Escape', False, 'send-keys -X clear-selection', ''),
    ('copy-mode-vi', 'Space', False, 'send-keys -X begin-selection', ''),
    ('copy-mode-vi', '#', False, 'send-keys -FX search-backward "#{copy_cursor_word}"', ''),
    ('copy-mode-vi', '$', False, 'send-keys -X end-of-line', ''),
    ('copy-mode-vi', '%', False, 'send-keys -X next-matching-bracket', ''),
    ('copy-mode-vi', '*', False, 'send-keys -FX search-forward "#{copy_cursor_word}"', ''),
    ('copy-mode-vi', ',', False, 'send-keys -X jump-reverse', ''),
    ('copy-mode-vi', '/', False, 'command-prompt -T search -p "(search down)" { send-keys -X search-forward "%%" }', ''),
    ('copy-mode-vi', '0', False, 'send-keys -X start-of-line', ''),
    ('copy-mode-vi', '1', False, 'command-prompt -N -I 1 -p (repeat) { send-keys -N "%%" }', ''),
    ('copy-mode-vi', '2', False, 'command-prompt -N -I 2 -p (repeat) { send-keys -N "%%" }', ''),
    ('copy-mode-vi', '3', False, 'command-prompt -N -I 3 -p (repeat) { send-keys -N "%%" }', ''),
    ('copy-mode-vi', '4', False, 'command-prompt -N -I 4 -p (repeat) { send-keys -N "%%" }', ''),
    ('copy-mode-vi', '5', False, 'command-prompt -N -I 5 -p (repeat) { send-keys -N "%%" }', ''),
    ('copy-mode-vi', '6', False, 'command-prompt -N -I 6 -p (repeat) { send-keys -N "%%" }', ''),
    ('copy-mode-vi', '7', False, 'command-prompt -N -I 7 -p (repeat) { send-keys -N "%%" }', ''),
    ('copy-mode-vi', '8', False, 'command-prompt -N -I 8 -p (repeat) { send-keys -N "%%" }', ''),
    ('copy-mode-vi', '9', False, 'command-prompt -N -I 9 -p (repeat) { send-keys -N "%%" }', ''),
    ('copy-mode-vi', ':', False, 'command-prompt -p "(goto line)" { send-keys -X goto-line "%%" }', ''),
    ('copy-mode-vi', ';', False, 'send-keys -X jump-again', ''),
    ('copy-mode-vi', '?', False, 'command-prompt -T search -p "(search up)" { send-keys -X search-backward "%%" }', ''),
    ('copy-mode-vi', 'A', False, 'send-keys -X append-selection-and-cancel', ''),
    ('copy-mode-vi', 'B', False, 'send-keys -X previous-space', ''),
    ('copy-mode-vi', 'D', False, 'send-keys -X copy-pipe-end-of-line-and-cancel', ''),
    ('copy-mode-vi', 'E', False, 'send-keys -X next-space-end', ''),
    ('copy-mode-vi', 'F', False, 'command-prompt -1 -p "(jump backward)" { send-keys -X jump-backward "%%" }', ''),
    ('copy-mode-vi', 'G', False, 'send-keys -X history-bottom', ''),
    ('copy-mode-vi', 'H', False, 'send-keys -X top-line', ''),
    ('copy-mode-vi', 'J', False, 'send-keys -X scroll-down', ''),
    ('copy-mode-vi', 'K', False, 'send-keys -X scroll-up', ''),
    ('copy-mode-vi', 'L', False, 'send-keys -X bottom-line', ''),
    ('copy-mode-vi', 'M', False, 'send-keys -X middle-line', ''),
    ('copy-mode-vi', 'N', False, 'send-keys -X search-reverse', ''),
    ('copy-mode-vi', 'P', False, 'send-keys -X toggle-position', ''),
    ('copy-mode-vi', 'T', False, 'command-prompt -1 -p "(jump to backward)" { send-keys -X jump-to-backward "%%" }', ''),
    ('copy-mode-vi', 'V', False, 'send-keys -X select-line', ''),
    ('copy-mode-vi', 'W', False, 'send-keys -X next-space', ''),
    ('copy-mode-vi', 'X', False, 'send-keys -X set-mark', ''),
    ('copy-mode-vi', '^', False, 'send-keys -X back-to-indentation', ''),
    ('copy-mode-vi', 'b', False, 'send-keys -X previous-word', ''),
    ('copy-mode-vi', 'e', False, 'send-keys -X next-word-end', ''),
    ('copy-mode-vi', 'f', False, 'command-prompt -1 -p "(jump forward)" { send-keys -X jump-forward "%%" }', ''),
    ('copy-mode-vi', 'g', False, 'send-keys -X history-top', ''),
    ('copy-mode-vi', 'h', False, 'send-keys -X cursor-left', ''),
    ('copy-mode-vi', 'j', False, 'send-keys -X cursor-down', ''),
    ('copy-mode-vi', 'k', False, 'send-keys -X cursor-up', ''),
    ('copy-mode-vi', 'l', False, 'send-keys -X cursor-right', ''),
    ('copy-mode-vi', 'n', False, 'send-keys -X search-again', ''),
    ('copy-mode-vi', 'o', False, 'send-keys -X other-end', ''),
    ('copy-mode-vi', 'q', False, 'send-keys -X cancel', ''),
    ('copy-mode-vi', 'r', False, 'send-keys -X refresh-from-pane', ''),
    ('copy-mode-vi', 't', False, 'command-prompt -1 -p "(jump to forward)" { send-keys -X jump-to-forward "%%" }', ''),
    ('copy-mode-vi', 'v', False, 'send-keys -X rectangle-toggle', ''),
    ('copy-mode-vi', 'w', False, 'send-keys -X next-word', ''),
    ('copy-mode-vi', 'z', False, 'send-keys -X scroll-middle', ''),
    ('copy-mode-vi', '{', False, 'send-keys -X previous-paragraph', ''),
    ('copy-mode-vi', '}', False, 'send-keys -X next-paragraph', ''),
    ('copy-mode-vi', 'MouseDown1Pane', False, 'select-pane', ''),
    ('copy-mode-vi', 'MouseDrag1Pane', False, 'select-pane \\; send-keys -X begin-selection', ''),
    ('copy-mode-vi', 'MouseDragEnd1Pane', False, 'send-keys -X copy-pipe-and-cancel', ''),
    ('copy-mode-vi', 'WheelUpPane', False, 'select-pane \\; send-keys -X -N 5 scroll-up', ''),
    ('copy-mode-vi', 'WheelDownPane', False, 'select-pane \\; send-keys -X -N 5 scroll-down', ''),
    ('copy-mode-vi', 'DoubleClick1Pane', False, 'select-pane \\; send-keys -X select-word \\; run-shell -d 0.3 \\; send-keys -X copy-pipe-and-cancel', ''),
    ('copy-mode-vi', 'TripleClick1Pane', False, 'select-pane \\; send-keys -X select-line \\; run-shell -d 0.3 \\; send-keys -X copy-pipe-and-cancel', ''),
    ('copy-mode-vi', 'BSpace', False, 'send-keys -X cursor-left', ''),
    ('copy-mode-vi', 'Home', False, 'send-keys -X start-of-line', ''),
    ('copy-mode-vi', 'End', False, 'send-keys -X end-of-line', ''),
    ('copy-mode-vi', 'NPage', False, 'send-keys -X page-down', ''),
    ('copy-mode-vi', 'PPage', False, 'send-keys -X page-up', ''),
    ('copy-mode-vi', 'Up', False, 'send-keys -X cursor-up', ''),
    ('copy-mode-vi', 'Down', False, 'send-keys -X cursor-down', ''),
    ('copy-mode-vi', 'Left', False, 'send-keys -X cursor-left', ''),
    ('copy-mode-vi', 'Right', False, 'send-keys -X cursor-right', ''),
    ('copy-mode-vi', 'M-x', False, 'send-keys -X jump-to-mark', ''),
    ('copy-mode-vi', 'C-Up', False, 'send-keys -X scroll-up', ''),
    ('copy-mode-vi', 'C-Down', False, 'send-keys -X scroll-down', ''),
    ('prefix', 'C-b', False, 'send-prefix', 'Send the prefix key'),
    ('prefix', 'C-o', False, 'rotate-window', 'Rotate through the panes'),
    ('prefix', 'C-z', False, 'suspend-client', 'Suspend the current client'),
    ('prefix', 'Space', False, 'next-layout', 'Select next layout'),
    ('prefix', '!', False, 'break-pane', 'Break pane to a new window'),
    ('prefix', '"', False, 'split-window', 'Split window vertically'),
    ('prefix', '#', False, 'list-buffers', 'List all paste buffers'),
    ('prefix', '$', False, 'command-prompt -I "#S" { rename-session "%%" }', 'Rename current session'),
    ('prefix', '%', False, 'split-window -h', 'Split window horizontally'),
    ('prefix', '&', False, 'confirm-before -p "kill-window #W? (y/n)" kill-window', 'Kill current window'),
    ('prefix', "'", False, 'command-prompt -T window-target -p index { select-window -t ":%%" }', 'Prompt for window index to select'),
    ('prefix', '(', False, 'switch-client -p', 'Switch to previous client'),
    ('prefix', ')', False, 'switch-client -n', 'Switch to next client'),
    ('prefix', ',', False, 'command-prompt -I "#W" { rename-window "%%" }', 'Rename current window'),
    ('prefix', '-', False, 'delete-buffer', 'Delete the most recent paste buffer'),
    ('prefix', '.', False, 'command-prompt -T target { move-window -t "%%" }', 'Move the current window'),
    ('prefix', '/', False, 'command-prompt -k -p key { list-keys -1N "%%" }', 'Describe key binding'),
    ('prefix', '0', False, 'select-window -t :=0', 'Select window 0'),
    ('prefix', '1', False, 'select-window -t :=1', 'Select window 1'),
    ('prefix', '2', False, 'select-window -t :=2', 'Select window 2'),
    ('prefix', '3', False, 'select-window -t :=3', 'Select window 3'),
    ('prefix', '4', False, 'select-window -t :=4', 'Select window 4'),
    ('prefix', '5', False, 'select-window -t :=5', 'Select window 5'),
    ('prefix', '6', False, 'select-window -t :=6', 'Select window 6'),
    ('prefix', '7', False, 'select-window -t :=7', 'Select window 7'),
    ('prefix', '8', False, 'select-window -t :=8', 'Select window 8'),
    ('prefix', '9', False, 'select-window -t :=9', 'Select window 9'),
    ('prefix', ':', False, 'command-prompt', 'Prompt for a command'),
    ('prefix', ';', False, 'last-pane', 'Move to the previously active pane'),
    ('prefix', '<', False, 'display-menu -T "#[align=centre]#{window_index}:#{window_name}" -x W -y W "#{?#{>:#{session_windows},1},,-}Swap Left" l { swap-window -t :-1 } "#{?#{>:#{session_windows},1},,-}Swap Right" r { swap-window -t :+1 } "#{?pane_marked_set,,-}Swap Marked" s { swap-window } \'\' Kill X { kill-window } Respawn R { respawn-window -k } "#{?pane_marked,Unmark,Mark}" m { select-pane -m } Rename n { command-prompt -F -I "#W" { rename-window -t "#{window_id}" "%%" } } \'\' "New After" w { new-window -a } "New At End" W { new-window }', ''),
    ('prefix', '=', False, 'choose-buffer -Z', 'Choose a paste buffer from a list'),
    ('prefix', '>', False, 'display-menu -T "#[align=centre]#{pane_index} (#{pane_id})" -x P -y P "#{?#{m/r:(copy|view)-mode,#{pane_mode}},Go To Top,}" < { send-keys -X history-top } "#{?#{m/r:(copy|view)-mode,#{pane_mode}},Go To Bottom,}" > { send-keys -X history-bottom } \'\' "#{?mouse_word,Search For #[underscore]#{=/9/...:mouse_word},}" C-r { if-shell -F "#{?#{m/r:(copy|view)-mode,#{pane_mode}},0,1}" "copy-mode -t=" ; send-keys -X -t = search-backward "#{q:mouse_word}" } "#{?mouse_word,Type #[underscore]#{=/9/...:mouse_word},}" C-y { copy-mode -q ; send-keys -l "#{q:mouse_word}" } "#{?mouse_word,Copy #[underscore]#{=/9/...:mouse_word},}" c { copy-mode -q ; set-buffer "#{q:mouse_word}" } "#{?mouse_line,Copy Line,}" l { copy-mode -q ; set-buffer "#{q:mouse_line}" } \'\' "#{?mouse_hyperlink,Type #[underscore]#{=/9/...:mouse_hyperlink},}" C-h { copy-mode -q ; send-keys -l "#{q:mouse_hyperlink}" } "#{?mouse_hyperlink,Copy #[underscore]#{=/9/...:mouse_hyperlink},}" h { copy-mode -q ; set-buffer "#{q:mouse_hyperlink}" } \'\' "Horizontal Split" h { split-window -h } "Vertical Split" v { split-window -v } \'\' "#{?#{>:#{window_panes},1},,-}Swap Up" u { swap-pane -U } "#{?#{>:#{window_panes},1},,-}Swap Down" d { swap-pane -D } "#{?pane_marked_set,,-}Swap Marked" s { swap-pane } \'\' Kill X { kill-pane } Respawn R { respawn-pane -k } "#{?pane_marked,Unmark,Mark}" m { select-pane -m } "#{?#{>:#{window_panes},1},,-}#{?window_zoomed_flag,Unzoom,Zoom}" z { resize-pane -Z }', ''),
    ('prefix', '?', False, 'list-keys -N', 'List key bindings'),
    ('prefix', 'C', False, 'customize-mode -Z', 'Customize options'),
    ('prefix', 'D', False, 'choose-client -Z', 'Choose and detach a client from a list'),
    ('prefix', 'E', False, 'select-layout -E', 'Spread panes out evenly'),
    ('prefix', 'L', False, 'switch-client -l', 'Switch to the last client'),
    ('prefix', 'M', False, 'select-pane -M', 'Clear the marked pane'),
    ('prefix', '[', False, 'copy-mode', 'Enter copy mode'),
    ('prefix', ']', False, 'paste-buffer -p', 'Paste the most recent paste buffer'),
    ('prefix', 'c', False, 'new-window', 'Create a new window'),
    ('prefix', 'd', False, 'detach-client', 'Detach the current client'),
    ('prefix', 'f', False, 'command-prompt { find-window -Z "%%" }', 'Search for a pane'),
    ('prefix', 'i', False, 'display-message', 'Display window information'),
    ('prefix', 'l', False, 'last-window', 'Select the previously current window'),
    ('prefix', 'm', False, 'select-pane -m', 'Toggle the marked pane'),
    ('prefix', 'n', False, 'next-window', 'Select the next window'),
    ('prefix', 'o', False, 'select-pane -t :.+', 'Select the next pane'),
    ('prefix', 'p', False, 'previous-window', 'Select the previous window'),
    ('prefix', 'q', False, 'display-panes', 'Display pane numbers'),
    ('prefix', 'r', False, 'refresh-client', 'Redraw the current client'),
    ('prefix', 's', False, 'choose-tree -Zs', 'Choose a session from a list'),
    ('prefix', 't', False, 'clock-mode', 'Show a clock'),
    ('prefix', 'w', False, 'choose-tree -Zw', 'Choose a window from a list'),
    ('prefix', 'x', False, 'confirm-before -p "kill-pane #P? (y/n)" kill-pane', 'Kill the active pane'),
    ('prefix', 'z', False, 'resize-pane -Z', 'Zoom the active pane'),
    ('prefix', '{', False, 'swap-pane -U', 'Swap the active pane with the pane above'),
    ('prefix', '}', False, 'swap-pane -D', 'Swap the active pane with the pane below'),
    ('prefix', '~', False, 'show-messages', 'Show messages'),
    ('prefix', 'DC', True, 'refresh-client -c', 'Reset so the visible part of the window follows the cursor'),
    ('prefix', 'PPage', False, 'copy-mode -u', 'Enter copy mode and scroll up'),
    ('prefix', 'Up', True, 'select-pane -U', 'Select the pane above the active pane'),
    ('prefix', 'Down', True, 'select-pane -D', 'Select the pane below the active pane'),
    ('prefix', 'Left', True, 'select-pane -L', 'Select the pane to the left of the active pane'),
    ('prefix', 'Right', True, 'select-pane -R', 'Select the pane to the right of the active pane'),
    ('prefix', 'M-1', False, 'select-layout even-horizontal', 'Set the even-horizontal layout'),
    ('prefix', 'M-2', False, 'select-layout even-vertical', 'Set the even-vertical layout'),
    ('prefix', 'M-3', False, 'select-layout main-horizontal', 'Set the main-horizontal layout'),
    ('prefix', 'M-4', False, 'select-layout main-vertical', 'Set the main-vertical layout'),
    ('prefix', 'M-5', False, 'select-layout tiled', 'Select the tiled layout'),
    ('prefix', 'M-n', False, 'next-window -a', 'Select the next window with an alert'),
    ('prefix', 'M-o', False, 'rotate-window -D', 'Rotate through the panes in reverse'),
    ('prefix', 'M-p', False, 'previous-window -a', 'Select the previous window with an alert'),
    ('prefix', 'M-Up', True, 'resize-pane -U 5', 'Resize the pane up by 5'),
    ('prefix', 'M-Down', True, 'resize-pane -D 5', 'Resize the pane down by 5'),
    ('prefix', 'M-Left', True, 'resize-pane -L 5', 'Resize the pane left by 5'),
    ('prefix', 'M-Right', True, 'resize-pane -R 5', 'Resize the pane right by 5'),
    ('prefix', 'C-Up', True, 'resize-pane -U', 'Resize the pane up'),
    ('prefix', 'C-Down', True, 'resize-pane -D', 'Resize the pane down'),
    ('prefix', 'C-Left', True, 'resize-pane -L', 'Resize the pane left'),
    ('prefix', 'C-Right', True, 'resize-pane -R', 'Resize the pane right'),
    ('prefix', 'S-Up', True, 'refresh-client -U 10', 'Move the visible part of the window up'),
    ('prefix', 'S-Down', True, 'refresh-client -D 10', 'Move the visible part of the window down'),
    ('prefix', 'S-Left', True, 'refresh-client -L 10', 'Move the visible part of the window left'),
    ('prefix', 'S-Right', True, 'refresh-client -R 10', 'Move the visible part of the window right'),
    ('root', 'MouseDown1Pane', False, 'select-pane -t = \\; send-keys -M', ''),
    ('root', 'MouseDown1Status', False, 'select-window -t =', ''),
    ('root', 'MouseDown2Pane', False, 'select-pane -t = \\; if-shell -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" { send-keys -M } { paste-buffer -p }', ''),
    ('root', 'MouseDown3Pane', False, 'if-shell -F -t = "#{||:#{mouse_any_flag},#{&&:#{pane_in_mode},#{?#{m/r:(copy|view)-mode,#{pane_mode}},0,1}}}" { select-pane -t = ; send-keys -M } { display-menu -T "#[align=centre]#{pane_index} (#{pane_id})" -t = -x M -y M "#{?#{m/r:(copy|view)-mode,#{pane_mode}},Go To Top,}" < { send-keys -X history-top } "#{?#{m/r:(copy|view)-mode,#{pane_mode}},Go To Bottom,}" > { send-keys -X history-bottom } \'\' "#{?mouse_word,Search For #[underscore]#{=/9/...:mouse_word},}" C-r { if-shell -F "#{?#{m/r:(copy|view)-mode,#{pane_mode}},0,1}" "copy-mode -t=" ; send-keys -X -t = search-backward "#{q:mouse_word}" } "#{?mouse_word,Type #[underscore]#{=/9/...:mouse_word},}" C-y { copy-mode -q ; send-keys -l "#{q:mouse_word}" } "#{?mouse_word,Copy #[underscore]#{=/9/...:mouse_word},}" c { copy-mode -q ; set-buffer "#{q:mouse_word}" } "#{?mouse_line,Copy Line,}" l { copy-mode -q ; set-buffer "#{q:mouse_line}" } \'\' "#{?mouse_hyperlink,Type #[underscore]#{=/9/...:mouse_hyperlink},}" C-h { copy-mode -q ; send-keys -l "#{q:mouse_hyperlink}" } "#{?mouse_hyperlink,Copy #[underscore]#{=/9/...:mouse_hyperlink},}" h { copy-mode -q ; set-buffer "#{q:mouse_hyperlink}" } \'\' "Horizontal Split" h { split-window -h } "Vertical Split" v { split-window -v } \'\' "#{?#{>:#{window_panes},1},,-}Swap Up" u { swap-pane -U } "#{?#{>:#{window_panes},1},,-}Swap Down" d { swap-pane -D } "#{?pane_marked_set,,-}Swap Marked" s { swap-pane } \'\' Kill X { kill-pane } Respawn R { respawn-pane -k } "#{?pane_marked,Unmark,Mark}" m { select-pane -m } "#{?#{>:#{window_panes},1},,-}#{?window_zoomed_flag,Unzoom,Zoom}" z { resize-pane -Z } }', ''),
    ('root', 'MouseDown3Status', False, 'display-menu -T "#[align=centre]#{window_index}:#{window_name}" -t = -x W -y W "#{?#{>:#{session_windows},1},,-}Swap Left" l { swap-window -t :-1 } "#{?#{>:#{session_windows},1},,-}Swap Right" r { swap-window -t :+1 } "#{?pane_marked_set,,-}Swap Marked" s { swap-window } \'\' Kill X { kill-window } Respawn R { respawn-window -k } "#{?pane_marked,Unmark,Mark}" m { select-pane -m } Rename n { command-prompt -F -I "#W" { rename-window -t "#{window_id}" "%%" } } \'\' "New After" w { new-window -a } "New At End" W { new-window }', ''),
    ('root', 'MouseDown3StatusLeft', False, 'display-menu -T "#[align=centre]#{session_name}" -t = -x M -y W Next n { switch-client -n } Previous p { switch-client -p } \'\' Renumber N { move-window -r } Rename n { command-prompt -I "#S" { rename-session "%%" } } \'\' "New Session" s { new-session } "New Window" w { new-window }', ''),
    ('root', 'MouseDrag1Pane', False, 'if-shell -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" { send-keys -M } { copy-mode -M }', ''),
    ('root', 'MouseDrag1Border', False, 'resize-pane -M', ''),
    ('root', 'WheelUpPane', False, 'if-shell -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" { send-keys -M } { copy-mode -e }', ''),
    ('root', 'WheelUpStatus', False, 'previous-window', ''),
    ('root', 'WheelDownStatus', False, 'next-window', ''),
    ('root', 'DoubleClick1Pane', False, 'select-pane -t = \\; if-shell -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" { send-keys -M } { copy-mode -H ; send-keys -X select-word ; run-shell -d 0.3 ; send-keys -X copy-pipe-and-cancel }', ''),
    ('root', 'TripleClick1Pane', False, 'select-pane -t = \\; if-shell -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" { send-keys -M } { copy-mode -H ; send-keys -X select-line ; run-shell -d 0.3 ; send-keys -X copy-pipe-and-cancel }', ''),
    ('root', 'M-MouseDown3Pane', False, 'display-menu -T "#[align=centre]#{pane_index} (#{pane_id})" -t = -x M -y M "#{?#{m/r:(copy|view)-mode,#{pane_mode}},Go To Top,}" < { send-keys -X history-top } "#{?#{m/r:(copy|view)-mode,#{pane_mode}},Go To Bottom,}" > { send-keys -X history-bottom } \'\' "#{?mouse_word,Search For #[underscore]#{=/9/...:mouse_word},}" C-r { if-shell -F "#{?#{m/r:(copy|view)-mode,#{pane_mode}},0,1}" "copy-mode -t=" ; send-keys -X -t = search-backward "#{q:mouse_word}" } "#{?mouse_word,Type #[underscore]#{=/9/...:mouse_word},}" C-y { copy-mode -q ; send-keys -l "#{q:mouse_word}" } "#{?mouse_word,Copy #[underscore]#{=/9/...:mouse_word},}" c { copy-mode -q ; set-buffer "#{q:mouse_word}" } "#{?mouse_line,Copy Line,}" l { copy-mode -q ; set-buffer "#{q:mouse_line}" } \'\' "#{?mouse_hyperlink,Type #[underscore]#{=/9/...:mouse_hyperlink},}" C-h { copy-mode -q ; send-keys -l "#{q:mouse_hyperlink}" } "#{?mouse_hyperlink,Copy #[underscore]#{=/9/...:mouse_hyperlink},}" h { copy-mode -q ; set-buffer "#{q:mouse_hyperlink}" } \'\' "Horizontal Split" h { split-window -h } "Vertical Split" v { split-window -v } \'\' "#{?#{>:#{window_panes},1},,-}Swap Up" u { swap-pane -U } "#{?#{>:#{window_panes},1},,-}Swap Down" d { swap-pane -D } "#{?pane_marked_set,,-}Swap Marked" s { swap-pane } \'\' Kill X { kill-pane } Respawn R { respawn-pane -k } "#{?pane_marked,Unmark,Mark}" m { select-pane -m } "#{?#{>:#{window_panes},1},,-}#{?window_zoomed_flag,Unzoom,Zoom}" z { resize-pane -Z }', ''),
    ('root', 'M-MouseDown3Status', False, 'display-menu -T "#[align=centre]#{window_index}:#{window_name}" -t = -x W -y W "#{?#{>:#{session_windows},1},,-}Swap Left" l { swap-window -t :-1 } "#{?#{>:#{session_windows},1},,-}Swap Right" r { swap-window -t :+1 } "#{?pane_marked_set,,-}Swap Marked" s { swap-window } \'\' Kill X { kill-window } Respawn R { respawn-window -k } "#{?pane_marked,Unmark,Mark}" m { select-pane -m } Rename n { command-prompt -F -I "#W" { rename-window -t "#{window_id}" "%%" } } \'\' "New After" w { new-window -a } "New At End" W { new-window }', ''),
    ('root', 'M-MouseDown3StatusLeft', False, 'display-menu -T "#[align=centre]#{session_name}" -t = -x M -y W Next n { switch-client -n } Previous p { switch-client -p } \'\' Renumber N { move-window -r } Rename n { command-prompt -I "#S" { rename-session "%%" } } \'\' "New Session" s { new-session } "New Window" w { new-window }', ''),
]
