"""Ready-made commands offered by the binding editor, and quick-start presets."""

# (label, command)
COMMAND_PRESETS = [
    ("Panes", [
        ("Split left/right (keep current dir)",
         'split-window -h -c "#{pane_current_path}"'),
        ("Split top/bottom (keep current dir)",
         'split-window -v -c "#{pane_current_path}"'),
        ("Select pane left", "select-pane -L"),
        ("Select pane down", "select-pane -D"),
        ("Select pane up", "select-pane -U"),
        ("Select pane right", "select-pane -R"),
        ("Resize pane left 5", "resize-pane -L 5"),
        ("Resize pane down 5", "resize-pane -D 5"),
        ("Resize pane up 5", "resize-pane -U 5"),
        ("Resize pane right 5", "resize-pane -R 5"),
        ("Zoom pane", "resize-pane -Z"),
        ("Kill pane (confirm)", 'confirm-before -p "kill-pane #P? (y/n)" kill-pane'),
        ("Break pane to window", "break-pane"),
        ("Swap pane with next", "swap-pane -D"),
        ("Swap pane with previous", "swap-pane -U"),
        ("Toggle synchronize-panes", "set-window-option synchronize-panes"),
        ("Show pane numbers", "display-panes"),
        ("Last pane", "last-pane"),
    ]),
    ("Windows", [
        ("New window (keep current dir)",
         'new-window -c "#{pane_current_path}"'),
        ("New window", "new-window"),
        ("Next window", "next-window"),
        ("Previous window", "previous-window"),
        ("Last window", "last-window"),
        ("Rename window", 'command-prompt -I "#W" { rename-window "%%" }'),
        ("Kill window (confirm)",
         'confirm-before -p "kill-window #W? (y/n)" kill-window'),
        ("Move window left", "swap-window -t -1 -d"),
        ("Move window right", "swap-window -t +1 -d"),
        ("Choose window", "choose-tree -Zw"),
        ("Next layout", "next-layout"),
        ("Even horizontal layout", "select-layout even-horizontal"),
        ("Even vertical layout", "select-layout even-vertical"),
        ("Tiled layout", "select-layout tiled"),
    ]),
    ("Sessions", [
        ("Choose session", "choose-tree -Zs"),
        ("New session", "new-session"),
        ("Rename session", 'command-prompt -I "#S" { rename-session "%%" }'),
        ("Detach", "detach-client"),
        ("Next session", "switch-client -n"),
        ("Previous session", "switch-client -p"),
        ("Last session", "switch-client -l"),
    ]),
    ("Copy mode", [
        ("Enter copy mode", "copy-mode"),
        ("Paste buffer", "paste-buffer"),
        ("Choose buffer", "choose-buffer -Z"),
        ("vi: begin selection", "send-keys -X begin-selection"),
        ("vi: rectangle toggle", "send-keys -X rectangle-toggle"),
        ("Copy selection", "send-keys -X copy-selection-and-cancel"),
        ("Copy to system clipboard (Linux, xclip)",
         'send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"'),
        ("Copy to system clipboard (Wayland)",
         'send-keys -X copy-pipe-and-cancel "wl-copy"'),
        ("Copy to system clipboard (macOS)",
         'send-keys -X copy-pipe-and-cancel "pbcopy"'),
        ("Cancel", "send-keys -X cancel"),
    ]),
    ("Misc", [
        ("Reload config", 'source-file ~/.tmux.conf \\; display-message "Config reloaded"'),
        ("Command prompt", "command-prompt"),
        ("Send prefix", "send-prefix"),
        ("List keys", "list-keys -N"),
        ("Clear history", "clear-history"),
        ("Toggle mouse", "set-option -g mouse"),
        ("Toggle status line", "set-option -g status"),
        ("Popup shell", 'display-popup -E -d "#{pane_current_path}"'),
        ("Clock", "clock-mode"),
        ("Show messages", "show-messages"),
        ("Run shell command…", "run-shell 'echo hello'"),
    ]),
]


# Quick-start presets: (label, description, option values, bindings,
# unbinds). Bindings are (table, key, repeat, command); unbinds (table, key).
QUICK_PRESETS = [
    ("Sensible defaults",
     "Mouse on, 1-based indexes, fast escape, big history, true colour.",
     {
         "mouse": "on",
         "base-index": "1",
         "pane-base-index": "1",
         "renumber-windows": "on",
         "escape-time": "10",
         "history-limit": "50000",
         "display-time": "2000",
         "focus-events": "on",
         "default-terminal": "tmux-256color",
         "terminal-features": ["xterm*:RGB"],
     }, [], []),
    ("Ctrl-a prefix (screen style)",
     "Use C-a as the prefix and free C-b.",
     {"prefix": "C-a"},
     [("prefix", "C-a", False, "send-prefix")],
     [("prefix", "C-b")]),
    ("Intuitive splits",
     "| and - split in the current directory; c opens windows there too.",
     {},
     [("prefix", "|", False, 'split-window -h -c "#{pane_current_path}"'),
      ("prefix", "-", False, 'split-window -v -c "#{pane_current_path}"'),
      ("prefix", "c", False, 'new-window -c "#{pane_current_path}"')],
     [("prefix", '"'), ("prefix", "%")]),
    ("Vim-style navigation",
     "vi keys; hjkl to move, HJKL to resize, v/y in copy mode.",
     {"mode-keys": "vi", "status-keys": "vi"},
     [("prefix", "h", False, "select-pane -L"),
      ("prefix", "j", False, "select-pane -D"),
      ("prefix", "k", False, "select-pane -U"),
      ("prefix", "l", False, "select-pane -R"),
      ("prefix", "H", True, "resize-pane -L 5"),
      ("prefix", "J", True, "resize-pane -D 5"),
      ("prefix", "K", True, "resize-pane -U 5"),
      ("prefix", "L", True, "resize-pane -R 5"),
      ("copy-mode-vi", "v", False, "send-keys -X begin-selection"),
      ("copy-mode-vi", "C-v", False, "send-keys -X rectangle-toggle"),
      ("copy-mode-vi", "y", False, "send-keys -X copy-selection-and-cancel")],
     []),
    ("Alt-arrow pane switching",
     "Switch panes with Alt+arrow keys without the prefix.",
     {},
     [("root", "M-Left", False, "select-pane -L"),
      ("root", "M-Right", False, "select-pane -R"),
      ("root", "M-Up", False, "select-pane -U"),
      ("root", "M-Down", False, "select-pane -D")],
     []),
    ("Reload config key",
     "prefix r reloads ~/.tmux.conf.",
     {},
     [("prefix", "r", False,
       'source-file ~/.tmux.conf \\; display-message "Config reloaded"')],
     []),
    ("Minimal dark status bar",
     "A clean dark status line with highlighted current window.",
     {
         "status-style": "bg=colour235,fg=colour250",
         "status-left": " #S ",
         "status-left-style": "bg=colour33,fg=colour231,bold",
         "status-left-length": "30",
         "status-right": " %Y-%m-%d %H:%M ",
         "status-right-style": "bg=colour238,fg=colour250",
         "window-status-format": " #I:#W ",
         "window-status-current-format": " #I:#W ",
         "window-status-current-style": "bg=colour33,fg=colour231,bold",
         "window-status-separator": "",
         "pane-border-style": "fg=colour238",
         "pane-active-border-style": "fg=colour33",
         "message-style": "bg=colour33,fg=colour231",
     }, [], []),
]


# Example values offered by the format builder: option -> [(label, format)].
FORMAT_EXAMPLES = {
    "status-left": [
        ("tmux default", "[#{session_name}] "),
        ("Session name, highlighted", "#[bg=colour33,fg=colour231,bold] #S #[default] "),
        ("Turns red while prefix is pressed",
         "#{?client_prefix,#[bg=red],#[bg=colour33]}#[fg=colour231] #S #[default] "),
        ("Session : window : pane", "#[fg=green]#S #[fg=yellow]#I #[fg=cyan]#P #[default]"),
        ("Host name", "#[fg=colour245]#h #[default]"),
    ],
    "status-right": [
        ("tmux default",
         '#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}"#{=21:pane_title}" %H:%M %d-%b-%y'),
        ("Date and time", " %Y-%m-%d %H:%M "),
        ("Prefix indicator + time", "#{?client_prefix,#[reverse] PREFIX #[noreverse] ,}%H:%M "),
        ("Host and time", "#[fg=colour245]#H #[fg=colour250]%a %d %b %H:%M "),
        ("Load average (runs a shell command)",
         "#(cut -d' ' -f1-3 /proc/loadavg) %H:%M "),
        ("Current directory", "#[fg=colour245]#{b:pane_current_path} "),
        ("Sync-panes warning", "#{?pane_synchronized,#[bg=red] SYNC #[default] ,}%H:%M "),
    ],
    "window-status-format": [
        ("tmux default", "#I:#W#{?window_flags,#{window_flags}, }"),
        ("Padded, no flags", " #I:#W "),
        ("Index and directory", " #I #{b:pane_current_path} "),
        ("Zoom marker", " #I:#W#{?window_zoomed_flag, (zoomed),} "),
    ],
    "window-status-current-format": [
        ("tmux default", "#I:#W#{?window_flags,#{window_flags}, }"),
        ("Padded, bold", "#[bold] #I:#W #[nobold]"),
        ("Arrow markers", "▶ #I:#W ◀"),
        ("Index and directory", " #I #{b:pane_current_path} "),
    ],
    "window-status-separator": [
        ("tmux default (space)", " "),
        ("None", ""),
        ("Bar", " | "),
    ],
    "pane-border-format": [
        ("tmux default", '#{?pane_active,#[reverse],}#{pane_index}#[default] "#{pane_title}"'),
        ("Index and command", " #P: #{pane_current_command} "),
        ("Index and directory", " #P #{b:pane_current_path} "),
        ("Size", " #P #{pane_width}x#{pane_height} "),
    ],
    "automatic-rename-format": [
        ("tmux default", "#{?pane_in_mode,[tmux],#{pane_current_command}}#{?pane_dead,[dead],}"),
        ("Current directory name", "#{b:pane_current_path}"),
        ("Command in directory", "#{pane_current_command}:#{b:pane_current_path}"),
    ],
    "set-titles-string": [
        ("tmux default", '#S:#I:#W - "#T" #{session_alerts}'),
        ("Session and window", "#S: #W"),
        ("Pane title", "#T"),
        ("Host, session, directory", "#h [#S] #{pane_current_path}"),
    ],
    "remain-on-exit-format": [
        ("tmux default",
         "Pane is dead (#{?#{!=:#{pane_dead_status},},status #{pane_dead_status},}"
         "#{?#{!=:#{pane_dead_signal},},signal #{pane_dead_signal},}, #{t:pane_dead_time})"),
        ("Short", "[exited #{pane_dead_status}] press prefix x to close"),
    ],
    "status-format": [
        ("Pane list line (tmux default for line 2)",
         "#[align=centre]#{P:#{?pane_active,#[reverse],}#{pane_index}[#{pane_width}x#{pane_height}]#[default] }"),
        ("Centred window list",
         "#[align=centre]#{W:#[fg=colour245] #I:#W ,#[fg=colour231,bold] #I:#W #[nobold]}"),
        ("Left / centre / right",
         "#[align=left] #S #[align=centre]#{W: #I:#W , [#I:#W] }#[align=right]%H:%M "),
        ("Clock only, right aligned", "#[align=right] %a %d %b %H:%M "),
    ],
}
